/**
 * Application-facing aliases over the generated schema (types.generated.ts). Generated by
 * `make gen-types` from the real, running API — never hand-duplicated. See
 * docs/specs/a8-frontend-dashboard.md §5.
 */
import type { components } from "./types.generated";

export type AnomalyView = components["schemas"]["AnomalyView"];
export type Counters = components["schemas"]["Counters"];
export type DeviceActivity = components["schemas"]["DeviceActivity"];
export type DeviceUpdate = components["schemas"]["DeviceUpdate"];
export type DeviceView = components["schemas"]["DeviceView"];
export type DomainCount = components["schemas"]["DomainCount"];
export type HealthResponse = components["schemas"]["HealthResponse"];
export type HistoryPoint = components["schemas"]["HistoryPoint"];
export type HistoryResponse = components["schemas"]["HistoryResponse"];
export type IncidentEventView = components["schemas"]["IncidentEventView"];
export type IncidentView = components["schemas"]["IncidentView"];
export type LoginRequest = components["schemas"]["LoginRequest"];
export type OverviewResponse = components["schemas"]["OverviewResponse"];
export type ProviderStatusView = components["schemas"]["ProviderStatus"];
export type QueryLogEntry = components["schemas"]["QueryLogEntry"];
export type QueryPage = components["schemas"]["QueryPage"];
export type SessionView = components["schemas"]["SessionView"];
export type SystemMetrics = components["schemas"]["SystemMetrics"];

export type Resolution = HistoryResponse["resolution"];
export type QueryOutcome = QueryLogEntry["outcome"];
export type IncidentState = IncidentView["state"];
export type HealthStatus = ProviderStatusView["status"];
export type Role = SessionView["role"];
export type IncidentSeverity = NonNullable<IncidentEventView["severity"]>;
export type AnomalySeverity = AnomalyView["severity"];

/**
 * `GET /api/v1/config` has no Pydantic `response_model` — `build_config_view()` in
 * `src/home_dns/api/views.py` returns a plain allow-listed `dict[str, Any]` on purpose (so a
 * future secret field can't leak by accident), so openapi-typescript can only generate
 * `{[key: string]: unknown}` for it. This is the one endpoint with no schema to generate from;
 * hand-written here to mirror `build_config_view()` exactly, not a duplicated schema.
 */
export interface GroupView {
  id: string;
  description: string;
  policy: string;
}

export interface BlocklistSourceView {
  id: string;
  name: string;
  categories: string[];
  update_interval_hours: number;
  /** Live per-source read, enriched by `config()` in views.py — not part of the cached config. */
  last_activated_at: string | null;
}

export interface StorageThresholdsView {
  healthy_below: number;
  warning_from: number;
  auto_cleanup_from: number;
  emergency_from: number;
}

export interface RetentionPolicyView {
  logs_max_bytes: number;
  logs_backup_count: number;
  temp_max_age_hours: number;
  backups_keep: number;
  query_history_days: number;
}

export interface MetricsConfigView {
  poll_interval_seconds: number;
  flush_interval_seconds: number;
  timezone: string;
  minute_retention_hours: number;
  hour_retention_days: number;
  day_retention_days: number;
}

export interface ConfigView {
  dns_provider: string;
  notifier: string;
  groups: GroupView[];
  policies: unknown[];
  blocklist_sources: BlocklistSourceView[];
  storage: {
    thresholds_percent: StorageThresholdsView;
    retention: RetentionPolicyView;
  };
  metrics: MetricsConfigView;
}

/** Query parameters for GET /api/v1/metrics/history (views.py `metrics_history`). */
export interface HistoryQuery {
  resolution?: Resolution;
  since?: string;
  until?: string;
  device_id?: number;
  [key: string]: string | number | boolean | undefined | null;
}

/** Query parameters for GET /api/v1/queries (views.py `queries`). */
export interface QueriesQuery {
  since?: string;
  until?: string;
  client?: string;
  domain?: string;
  outcome?: QueryOutcome;
  limit?: number;
  cursor?: string;
  [key: string]: string | number | boolean | undefined | null;
}
