/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Info */
        get: operations["session_info_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_api_v1_devices__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Device */
        patch: operations["update_device_api_v1_devices__device_id__patch"];
        trace?: never;
    };
    "/api/v1/devices/{device_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Device Activity */
        get: operations["device_activity_api_v1_devices__device_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics History */
        get: operations["metrics_history_api_v1_metrics_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Queries */
        get: operations["queries_api_v1_queries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incident History */
        get: operations["incident_history_api_v1_incidents_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config
         * @description A shallow, per-request enrichment of the cached ``config_view`` with live per-source
         *     blocklist-freshness timestamps — the base view is built once at startup (see
         *     ``build_config_view``), so a live timestamp cannot be baked into it without going stale.
         */
        get: operations["config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Counters */
        Counters: {
            /** Total */
            total: number;
            /** Blocked */
            blocked: number;
            /** Allowed */
            allowed: number;
            /** Cached */
            cached: number;
            /** Forwarded */
            forwarded: number;
            /** Block Percentage */
            block_percentage: number;
            /** Cache Hit Ratio */
            cache_hit_ratio: number | null;
            /** Latency P50 Ms */
            latency_p50_ms: number | null;
            /** Latency P95 Ms */
            latency_p95_ms: number | null;
            /** Blocked By Source */
            blocked_by_source: {
                [key: string]: number;
            };
        };
        /** DeviceActivity */
        DeviceActivity: {
            /** Device Id */
            device_id: number;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /**
             * Truncated
             * @description More entries existed than were scanned
             */
            truncated: boolean;
            /** Top Domains */
            top_domains: components["schemas"]["DomainCount"][];
            /** Top Blocked */
            top_blocked: components["schemas"]["DomainCount"][];
            /** Recent */
            recent: components["schemas"]["QueryLogEntry"][];
        };
        /** DeviceUpdate */
        DeviceUpdate: {
            /** Custom Name */
            custom_name?: string | null;
            /** Group Id */
            group_id?: string | null;
        };
        /** DeviceView */
        DeviceView: {
            /** Device Id */
            device_id: number;
            /** Name */
            name: string;
            /** Custom Name */
            custom_name: string | null;
            /** Hostname */
            hostname: string | null;
            /** Mac */
            mac: string | null;
            /** Addresses */
            addresses: string[];
            /** Group Id */
            group_id: string;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            last_24h: components["schemas"]["Counters"];
        };
        /** DiskUsage */
        DiskUsage: {
            /** Total Bytes */
            total_bytes: number;
            /** Used Bytes */
            used_bytes: number;
            /** Free Bytes */
            free_bytes: number;
            /** Used Percent */
            readonly used_percent: number;
        };
        /** DomainCount */
        DomainCount: {
            /** Domain */
            domain: string;
            /** Count */
            count: number;
        };
        /**
         * Environment
         * @enum {string}
         */
        Environment: "development" | "production";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
            environment: components["schemas"]["Environment"];
            provider: components["schemas"]["ProviderHealthView"];
            /** Version */
            version: string;
        };
        /**
         * HealthStatus
         * @enum {string}
         */
        HealthStatus: "ok" | "degraded" | "down";
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * Bucket Start
             * Format: date-time
             */
            bucket_start: string;
            /**
             * Bucket End
             * Format: date-time
             */
            bucket_end: string;
            /** Queries Per Second */
            queries_per_second: number;
            counters: components["schemas"]["Counters"];
        };
        /** HistoryResponse */
        HistoryResponse: {
            resolution: components["schemas"]["Resolution"];
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /**
             * Until
             * Format: date-time
             */
            until: string;
            /** Device Id */
            device_id: number | null;
            /**
             * Points
             * @description Buckets without queries are omitted
             */
            points: components["schemas"]["HistoryPoint"][];
        };
        /**
         * IncidentEventView
         * @description One persisted opened/recovered transition. Deliberately minimal — see
         *     storage/dashboard.py's ``incident_events`` table doc. No "notified" flag: the CLI monitoring
         *     command does not itself confirm a Telegram send, so that status is not actually known here and
         *     is not fabricated.
         */
        IncidentEventView: {
            /** Check Name */
            check_name: string;
            /** Transition */
            transition: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Severity */
            severity: ("critical" | "warning" | "info") | null;
        };
        /**
         * IncidentState
         * @enum {string}
         */
        IncidentState: "ok" | "suspect" | "incident" | "recovering";
        /** IncidentView */
        IncidentView: {
            /** Check Name */
            check_name: string;
            state: components["schemas"]["IncidentState"];
            /** Opened At */
            opened_at: string | null;
            /** Last Change At */
            last_change_at: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** OverviewResponse */
        OverviewResponse: {
            provider: components["schemas"]["ProviderStatus"];
            /**
             * Metrics As Of
             * @description Collector watermark of the last flush; newer queries are not counted yet
             */
            metrics_as_of: string | null;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            last_24h: components["schemas"]["Counters"];
            /**
             * Queries Per Second
             * @description Average over the last 5 flushed minutes
             */
            queries_per_second: number;
            system: components["schemas"]["SystemMetrics"] | null;
            /** Open Incidents */
            open_incidents: number;
            /** Last Backup At */
            last_backup_at: string | null;
            /** Last Blocklist Update At */
            last_blocklist_update_at: string | null;
            storage: components["schemas"]["DiskUsage"];
        };
        /** ProviderHealthView */
        ProviderHealthView: {
            /** Name */
            name: string;
            status: components["schemas"]["HealthStatus"];
        };
        /** ProviderStatus */
        ProviderStatus: {
            /** Name */
            name: string;
            status: components["schemas"]["HealthStatus"];
        };
        /** QueryLogEntry */
        QueryLogEntry: {
            /** Id */
            id: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Client Address */
            client_address: string;
            /** Domain */
            domain: string;
            /** Query Type */
            query_type: string;
            outcome: components["schemas"]["QueryOutcome"];
            /** Blocked By */
            blocked_by?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
        };
        /**
         * QueryOutcome
         * @description Pi-hole's 19 query statuses collapsed; mapping in docs/specs/a7-backend.md §3.
         * @enum {string}
         */
        QueryOutcome: "forwarded" | "cached" | "blocked" | "other";
        /**
         * QueryPage
         * @description Entries newest first. Pass ``next_cursor`` back to continue; None means no more.
         */
        QueryPage: {
            /** Entries */
            entries: components["schemas"]["QueryLogEntry"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * Resolution
         * @enum {string}
         */
        Resolution: "minute" | "hour" | "day";
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "viewer";
        /** SessionView */
        SessionView: {
            /** Username */
            username: string;
            role: components["schemas"]["Role"];
            /** Csrf Token */
            csrf_token: string;
        };
        /** SystemMetrics */
        SystemMetrics: {
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Cpu Percent */
            cpu_percent: number;
            /** Load 1M */
            load_1m: number;
            /** Memory Total Bytes */
            memory_total_bytes: number;
            /** Memory Used Bytes */
            memory_used_bytes: number;
            /** Temperature Celsius */
            temperature_celsius?: number | null;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    session_info_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
        };
    };
    overview_api_v1_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceView"][];
                };
            };
        };
    };
    get_device_api_v1_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_api_v1_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    device_activity_api_v1_devices__device_id__activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceActivity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_history_api_v1_metrics_history_get: {
        parameters: {
            query?: {
                resolution?: components["schemas"]["Resolution"];
                since?: string | null;
                until?: string | null;
                device_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queries_api_v1_queries_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                client?: string | null;
                domain?: string | null;
                outcome?: components["schemas"]["QueryOutcome"] | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_v1_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentView"][];
                };
            };
        };
    };
    incident_history_api_v1_incidents_history_get: {
        parameters: {
            query?: {
                limit?: number;
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentEventView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
